baseurl: ""
url: "https://www.unremarkablegames.com"
author: "Karl McClendon"

collections:
  notes:
    output: true
    permalink: /notes/:name

defaults:
  - scope:
      path: ""
    values:
      layout: default
